# DB
dbKind: mysql

mysql:
  class: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  url: jdbc:log4jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8&rewriteBatchedStatements=true

oracle:
  class: oracle.jdbc.driver.OracleDriver
  url: jdbc:oracle:thin:@localhost:1521:orcl

#
spring:
  datasource:
    hikari:
      driver-class-name: ${${dbKind}.class}
      jdbc-url: ${${dbKind}.url}
      username: root
      password: lgu1234!
      maximum-pool-size: 5
      auto-commit: true
      max-lifetime: 600000
      connection-timeout: 3000
      idle-timeout: 500000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

server:
  address: localhost
  port: 8080
  servlet:
    context-path: /
  error:
    path: /error.do

#CONNECTION
http:
  connectionpoolcount: 2

ENCRYPT: AES
DECRYPT: AES

SECRETKEY: 123456789123456789
---
logging:
  file:
    path: D:/ex/ably/logs
  level:
    root: info
    org.springframework.web: info
